# Generated by Django 5.0 on 2023-12-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
